default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: chatruby_development

test:
  <<: *default
  database: chatruby_test

production:
  <<: *default
  database: chatruby_production
  username: <%= Rails.application.credentials.dig(:production, :db_username) %>
  password: <%= Rails.application.credentials.dig(:production, :db_password) %>
  host: <%= Rails.application.credentials.dig(:production, :db_host) %>
  port: <%= Rails.application.credentials.dig(:production, :db_port) %>
